teamdream/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from teamdreamapp.models import *
from teamdreamapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    # The following url is set-up to help in logging the user in--look at templates/registration/login.html file
    url(r'accounts/', include('django.contrib.auth.urls')),
    # The following url is set up to help logout the user--look at the views/auth/logout.py file
    url(r'^logout/$', logout_user, name='logout'),
    # The following url is set up to look-up all the urls listed in urls.py file of the teamdreamapp
    url(r'^', include('teamdreamapp.urls')),
]

teamdreamapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = "teamdreamapp"

urlpatterns = [
    url(r'^$', go_home, name='home'),
    url(r'^actionitems$', action_item_list, name='actionitems'),
    # The following url takes you to the register_user method in views/auth/registration.py file.
    url(r'^register$', register_user, name='register'),
    # The following url takes you to the register_form method in views/auth/registerform.py file.
    url(r'^register/form$', register_form, name='registerform'),
    # The following url takes you to the login_form method in views/auth/loginform.py file.
    url(r'^accounts/login$', login_form, name='login'),
    # The following url takes you to the logout_user method in views/auth/logout.py file.
    url(r'^logout$', logout_user, name='logout'),
    # The following url takes you to the sprint_addform method in views/sprints/addform.py file.
    url(r'^sprints/addform$', sprint_addform, name='sprintaddform'),
    # The following url takes you to the add_sprint method in views/sprints/addsprint.py file.
    url(r'^addsprint$', add_sprint, name='addsprint'),
    # The following url takes you to the sprint_list method in views/sprints/list.py file.
    url(r'^sprints/list$', sprint_list, name='sprintlist'),
    # The following url takes you to the itemtype_addform method in views/itemtypes/additemform.py file.
    url(r'^itemtypes/addform$', itemtype_addform, name='itemtypeaddform'),
    # The following url takes you to the add_itemtype method in views/itemtypes/additemtype.py file.
    url(r'^additemtype$', add_itemtype, name='additemtype'),
    # The following url takes you to the itemtype_list method in views/itemtypes/list.py file.
    url(r'^itemtypes/list$', itemtype_list, name='itemtypelist'),
    # The following url takes you to the action_item_addform method in views/actionitems/addform.py file.
    url(r'^actionitems/addform$', action_item_addform, name='actionitemaddform'),
    # The following url takes you to the action_item_addaction method in views/actionitems/addaction.py file.
    url(r'^actionitems/addaction$', action_item_addaction,
        name='actionitemaddaction'),
    # The following url takes you to the action_item_details method in views/actionitems/actionitemdet.py file.
    path('actionitem/<int:actionitem_id>/<str:whichlist>',
         action_item_details, name='actionitem'),
    # The following url takes you to the action_edit_form method in views/actionitems/editform.py file.
    path('actionitems/(?P<actionitem_id>[0-9]+)/<str:whichlist>/form',
         actionitem_edit_form, name='actionitem_edit_form'),
    # The following url takes you to the action_item_list_completed method in views/actionitems/listcompleted.py file.
    url(r'^actionitems/completed$', action_item_list_completed,
        name='actionitemscompleted'),
    # The following url takes you to the action_item_list_presprint method in views/actionitems/listpresprint.py file.
    url(r'^actionitems/presprintreview$', action_item_list_presprint,
        name='actionitemspresprint'),
]

teamdreamapp/models/actionitem.py
from django.db import models
from django.urls import reverse
from .sprint import Sprint
from .itemtype import ItemType


class ActionItem(models.Model):

    sprint = models.ForeignKey(
        Sprint, related_name="sprints",
        null=True,
        blank=True,
        on_delete=models.CASCADE)
    itemtype = models.ForeignKey(
        ItemType, related_name="itemtypes",
        on_delete=models.CASCADE)
    description = models.CharField(max_length=50)
    start_date = models.DateField(null=True)
    finish_date = models.DateField(null=True)
    personal_benefit = models.CharField(max_length=50, blank=True, null=True)
    team_benefit = models.CharField(max_length=50, blank=True, null=True)
    presprint_review = models.BooleanField()

    class Meta:
        verbose_name = ("ActionItem")
        verbose_name_plural = ("ActionItems")

    def __str__(self):
        return f"Action Item Id: {self.pk} Description: {self.description} Associated Employee: {self.employee} Associated Sprint: {self.sprint} Associated Type: {self.itemtype}"

    def get_absolute_url(self):
        return reverse("ActionItem_detail", kwargs={"pk": self.pk})

teamdreamapp/models/employee.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department_name = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

teamdreamapp/models/itemtype.py
from django.db import models
from .employee import Employee
from django.urls import reverse


class ItemType(models.Model):

    employee = models.ForeignKey(
        Employee, related_name="itemtypeemployee",
        on_delete=models.CASCADE)
    action_desc = models.CharField(max_length=15)

    class Meta:
        verbose_name = ("ItemType")
        verbose_name_plural = ("ItemTypes")

    def __str__(self):
        return self.action_desc

    def get_absolute_url(self):
        return reverse("ItemType_detail", kwargs={"pk": self.pk})

teamdreamapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries


def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

teamdreamapp/models/sprint.py
from django.db import models
from .employee import Employee
from django.urls import reverse


class Sprint(models.Model):

    employee = models.ForeignKey(
        Employee, related_name="sprintemployee",
        on_delete=models.CASCADE)
    sprint_name = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        verbose_name = ("Sprint")
        verbose_name_plural = ("Sprints")

    def __str__(self):
        return self.sprint_name

    def get_absolute_url(self):
        return reverse("Sprint_detail", kwargs={"pk": self.pk})

teamdreamapp/views.py
from django.shortcuts import render

# Create your views here.

teamdreamapp/templates/actionitems/addform.html
{% extends 'shared/base.html' %}

{% block content %}
    <h3>Add An Action Item</h3>

{% comment %} The form action step below takes you to the url for this form--what happens when this form is submitted {% endcomment %}
{% comment %} The method is sent with it--Post {% endcomment %}

    <form action="{% url 'teamdreamapp:actionitemaddaction' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="actiondescription">Action Description: </label>
          <select id="actiondescription" type="text" name="actiondescription">
                {% for itemtype in all_itemtypes %}
                    <option value="{{ itemtype.id }}">{{ itemtype.action_desc }}</option>
                {% endfor %}
          </select>
      </fieldset>
      <fieldset>
          <label for="description">Description: </label>
          <input id="description" type="text" name="description">
      </fieldset>
      <fieldset>
          <label for="start_date">Start Date: </label>
          <input id="start_date" type="date" name="start_date">
      </fieldset>
      <fieldset>
          <label for="finish_date">Finish Date: </label>
          <input id="finish_date" type="date" name="finish_date">
          <label for="finish_comment">(Don't enter a date if this action item is NOT finished!)</label>
      </fieldset>
      <fieldset>
          <label for="personal_benefit">Personal Benefit: </label>
          <input id="personal_benefit" type="text" name="personal_benefit">
      </fieldset>
      <fieldset>
          <label for="team_benefit">Team Benefit: </label>
          <input id="team_benefit" type="text" name="team_benefit">
      </fieldset>
      <fieldset>
          <label for="sprintdescription">Sprint Description: </label>
          <select id="sprintdescription" type="text" name="sprintdescription">
                {% for sprint in all_sprints %}
                    <option value="{{ sprint.id }}">{{ sprint.sprint_name }}</option>
                {% endfor %}
          </select>
      </fieldset>
      <fieldset>
          <label for="presprintreview">Pre-Sprint Review: </label>
          <input id="presprintreview" type="checkbox" name="presprintreview" value=True>
      </fieldset>
      <input class="btn btn-primary" type="submit" value="Add Action Item" />
    </form>
{% endblock %}

teamdreamapp/templates/actionitems/detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <div class="widthclass">
            <h3>Action Item Detail</h3>
            <br>
            <div class="card cardclass" style="width: 60rem; background-color:lightyellow">
                <div class="widthclass">
                    <h3>Type of Action: {{ actionitemplus.action_desc }}</h3>
                    <h3>Description: {{ actionitemplus.description }}</h3>
                    <h3>From Which Sprint: {{ actionitemplus.sprint_name }}</h3>
                    <br>
                    <h4>Start Date: {{ actionitemplus.start_date }}</h4>
                    <h4>Finish Date: {{ actionitemplus.finish_date }}</h4>
                    <div>Personal Benefit: {{ actionitemplus.personal_benefit }}</div>
                    <div>Team Benefit: {{ actionitemplus.team_benefit }}</div>
                    <div>Pre-Sprint Review: {{ presprint_value }}</div>
                    <br>
                    <div style="display: flex">
                        <form action="{% url 'teamdreamapp:actionitem' actionitemplus.a2 whichlist %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="actual_method" value="DELETE">
                            <button class="btn btn-danger">Delete</button>
                        </form>
                        <form class="ml-3" action="{% url 'teamdreamapp:actionitem_edit_form' actionitemplus.a2 whichlist %}" method="GET">
                            {% csrf_token %}
                            <button class="btn btn-primary">Edit</button>
                        </form>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

teamdreamapp/templates/actionitems/editform.html
{% extends 'shared/base.html' %}

{% block content %}
    <h3>Edit An Action Item</h3>

{% comment %} The form action step below takes you to the url for this form--what happens when this form is submitted {% endcomment %}
{% comment %} The method is sent with it--Post {% endcomment %}

    <form action="{% url 'teamdreamapp:actionitem' actionitem.id whichlist %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="actiondescription">Action Description: </label>
          <select id="actiondescription" type="text" name="actiondescription">
                {% for itemtype in all_itemtypes %}
                    <option value="{{ itemtype.id }}">{{ itemtype.action_desc }}</option>
                {% endfor %}
          </select>
      </fieldset>
      <fieldset>
          <label for="description">Description: </label>
          <input id="description" type="text" name="description" value="{{ actionitem.description }}">
      </fieldset>
      <fieldset>
          <label for="start_date">Start Date: </label>
          <input id="start_date" type="date" name="start_date" value="{{ actionitem.start_date }}">
      </fieldset>
      <fieldset>
          <label for="finish_date">Finish Date: </label>
          <input id="finish_date" type="date" name="finish_date" value={{ actionitem.finish_date }}>
      </fieldset>
      <fieldset>
          <label for="personal_benefit">Personal Benefit: </label>
          <input id="personal_benefit" type="text" name="personal_benefit" value="{{ actionitem.personal_benefit }}">
      </fieldset>
      <fieldset>
          <label for="team_benefit">Team Benefit: </label>
          <input id="team_benefit" type="text" name="team_benefit" value="{{ actionitem.team_benefit }}">
      </fieldset>
      <fieldset>
          <label for="sprintdescription">Action Description: </label>
          <select id="sprintdescription" type="text" name="sprintdescription">
                {% for sprint in all_sprints %}
                    <option value="{{ sprint.id }}">{{ sprint.sprint_name }}</option>
                {% endfor %}
          </select>
      </fieldset>
      <fieldset>
          <label for="presprintreview">Pre-Sprint Review: </label>
          {% if actionitem.presprint_review == 1 %}
            <input id="presprintreview" type="checkbox" name="presprintreview" value=True checked>
          {% else %}
            <input id="presprintreview" type="checkbox" name="presprintreview" value=False>
          {% endif %}
      </fieldset>
        {% comment %} To differentiate the ACTUAL method being requested, a hidden field is being used. {% endcomment %}
        <input type="hidden" name="actual_method" value="PUT">
        <input class="btn btn-primary" type="submit" value="Update" />
    </form>
{% endblock %}

teamdreamapp/templates/actionitems/list.html
{% extends 'shared/base.html' %}

{% block content %}

    {% if whichlist == "all" %}
        <h2>All Action Items</h2>
    {% else %}
        {% if whichlist == "completed" %}
          <h2>Completed Action Items</h2>
        {% else %}
          <h2>Pre-Sprint Review Items</h2>
        {% endif %}
    {% endif %}

    <a class="addlink" href="{% url 'teamdreamapp:actionitemaddform' %}">Add An Action Item</a>

    <ol>
    {% for actionitem in all_actions %}
        <li>
            <a href="{% url 'teamdreamapp:actionitem' actionitem.id whichlist %}">{{ actionitem.description }}</a>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

teamdreamapp/templates/home/home.html
{% extends 'shared/base.html' %}

{% block content %}
    <br>
    <h3 class="subhead1">To Create Your FIRST Action Item FOR a Specific Sprint:</h3>

    <h5>[NOTE--Please follow the steps below in order]</h5>
    <br>
    <ol>
    <li>Click on 'Sprints' on the Menu Above and Add a Sprint</li>
    <br>
    <li>Click on 'Types of Actions' on the Menu Above and Add a Type of Action (Example choices:  Start, Stop, Continue, etc)</li>
    <br>
    <li>Click on 'All Action Items' on the Menu Above and then choose 'Add an Action Item'</li>
    </ol>

{% endblock %}

teamdreamapp/templates/itemtypes/addform.html
{% extends 'shared/base.html' %}

{% block content %}
    <h3>Add An Action Description</h3>

{% comment %} The form action step below takes you to the url for this form--what happens when this form is submitted {% endcomment %}
{% comment %} The method is sent with it--Post {% endcomment %}

    <form action="{% url 'teamdreamapp:additemtype' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="actiondesc">Action Description: </label>
          <input id="actiondesc" type="text" name="actiondesc">
      </fieldset>
      <input class="btn btn-primary" type="submit" value="Add Action Description" />
    </form>
{% endblock %}

teamdreamapp/templates/itemtypes/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h2>List of Action Type Descriptions</h2>

    <a class="addlink" href="{% url 'teamdreamapp:itemtypeaddform' %}">Add An Action Type Description</a>

    <ol>
    {% for itemtype in all_itemtypes %}
        <li>
            {{ itemtype.action_desc }}
        </li>
    {% endfor %}
    </ol>
{% endblock %}

teamdreamapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Team Dream</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .mainTitle {
    position: absolute;
    top: 10%;
    right: 50%;
    transform: translate(50%,-50%);
    text-transform: uppercase;
    font-family: verdana;
    font-size: 4em;
    font-weight: 700;
    color: blue;
    {% comment %} color: #f5f5f5; {% endcomment %}
    text-shadow: 1px 1px 1px #919191,
        1px 2px 1px #919191,
        1px 3px 1px #919191,
        1px 4px 1px #919191,
        1px 5px 1px #919191,
        1px 6px 1px #919191,
        1px 7px 1px #919191,
        1px 8px 1px #919191,
        1px 9px 1px #919191,
        1px 10px 1px #919191,
    1px 18px 6px rgba(16,16,16,0.4),
    1px 22px 10px rgba(16,16,16,0.2),
    1px 25px 35px rgba(16,16,16,0.2),
    1px 30px 60px rgba(16,16,16,0.4);
    }

        .subTitle {
            margin-left: 10px;
            font-style:  italic;
            font-weight:  bold;
            color: red;
        }

        .navList {
            list-style-type: none;
            display: flex;
            border: 1px solid lightgray;ma
            padding: 1em;
        }

        .navList__route {
            margin: 0 0.5em;
        }

        .widthclass {
            margin: 0 3em 2em 5em;
        }

        .cardclass {
            border: 5px solid red;
        }

        .addlink {
            margin-left: 10px;
            font-style:  italic;
            font-weight:  bold;
            font-size: 20px;
            color: green;
        }
    </style>
</head>

<body style="background-color:aqua">
    <p class="mainTitle">TEAM DREAM</p>
    <br><br><br><br>
    <p class="subTitle">A Personal Development Plan for Success</p>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'teamdreamapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:sprintlist' %}">Sprints</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:itemtypelist' %}">Types of Actions</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:actionitems' %}">All Action Items</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:actionitemscompleted' %}">Completed Action Items</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:actionitemspresprint' %}">Pre-Sprint Review Items</a></li>
            <li class="navList__route"><a href="{% url 'teamdreamapp:logout' %}">Logout</a></li>
        </ol>
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

teamdreamapp/templates/sprints/addform.html
{% extends 'shared/base.html' %}

{% block content %}
    <h3>Add A Sprint</h3>

{% comment %} The form action step below takes you to the url for this form--what happens when this form is submitted {% endcomment %}
{% comment %} The method is sent with it--Post {% endcomment %}

    <form action="{% url 'teamdreamapp:addsprint' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="sprintname">Name of Sprint: </label>
          <input id="sprintname" type="text" name="sprintname">
      </fieldset>
      <fieldset>
          <label for="startdate">Start Date: </label>
          <input id="startdate" type="date" name="startdate">
      </fieldset>
      <fieldset>
          <label for="enddate">End Date: </label>
          <input id="enddate" type="date" name="enddate">
      </fieldset>
      <input class="btn btn-primary" type="submit" value="Add Sprint" />
    </form>
{% endblock %}

teamdreamapp/templates/sprints/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h2>List of Sprints</h2>

    <a class="addlink" href="{% url 'teamdreamapp:sprintaddform' %}">Add A Sprint</a>

    <ol>
    {% for sprint in all_sprints %}
        <li>
            Sprint Name:  {{ sprint.sprint_name }}
            (Start Date: {{sprint.start_date}}
            End Date: {{sprint.end_date}})
        </li>
    {% endfor %}
    </ol>
{% endblock %}